# https://docs.docker.com/compose/yml/

version: '2'
services:
  backend:
    image: mgcrea/node-opencv:2.4
    command: "node lib"
    # command: "/usr/local/bin/npm install --verbose"
    working_dir: /srv/node
    network_mode: "host"
    container_name: test_opencv
    environment:
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/opencv/build/lib
      - NODE_ENV=production
    expose:
      - "3000"
    volumes:
      - .:/srv/node
      - /usr/lib/beignet:/usr/lib/beignet:ro
      - /srv/player/data/volumes/opencv:/volumes/opencv:rw
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/dri/card0:/dev/dri/card0"
